def
    try:




except Exception as ex:
    print(f'Eror information: {ex}')